In [1]:
import pandas as pd
import numpy as np

/Users/dhkim/PycharmProjects/untitled/venv/lib/python3.8/site-packages/pandas/compat/__init__.py:117: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)

In [5]:
naver_reveiw = pd.read_csv('../kakomap_crwal/data/starbucks/starbucks_review_total_before_process_200626.csv', sep='\t', index_col=0)

In [8]:
naver_reveiw_add = pd.read_excel('../kakomap_crwal/data/2020-07-09_14_32_3place_review.xlsx')
naver_reveiw_add

,loc_name,link,receipt_num,reviews,scores,dates,visit_num
0,스타벅스 부산교대역DT점,https://m.place.naver.com/restaurant/183480825...,3,"{0: '', 1: '새로 생긴 스벅이 담에도 또 와야징 주차창이 넘 작아요', 2...","{0: 4.0, 1: 4.5, 2: 5.0}","{0: '2020.07.08', 1: '2020.07.08', 2: '2020.07...","{0: '1번째 방문', 1: '2번째 방문', 2: '1번째 방문'}"
1,스타벅스 서귀포DT점,https://m.place.naver.com/restaurant/37053570/...,167,"{0: '맛있어용 대기가 좀 길엇어요ㅠ', 1: '굿', 2: '굿', 3: '전망...","{0: 4.5, 1: 5.0, 2: 5.0, 3: 3.0, 4: 4.0, 5: 4....","{0: '2020.07.09', 1: '2020.07.08', 2: '2020.07...","{0: '1번째 방문', 1: '8번째 방문', 2: '7번째 방문', 3: '1번..."
2,스타벅스 제주중문DT점,https://m.place.naver.com/restaurant/36952159/...,153,"{0: '', 1: '굿', 2: '굿', 3: '👍 늦게 갔더니 빵이 없네요ㅜㅜ'...","{0: 4.5, 1: 5.0, 2: 4.5, 3: 5.0, 4: 5.0, 5: 5....","{0: '2020.07.08', 1: '2020.07.08', 2: '2020.07...","{0: '1번째 방문', 1: '5번째 방문', 2: '1번째 방문', 3: '1번..."

In [13]:
naver_reveiw = pd.concat([naver_reveiw, naver_reveiw_add]).reset_index(drop=True)
naver_reveiw

,loc_name,address,num_review,link,receipt_num,reviews,scores,dates,visit_num
0,스타벅스 연희DT점,"연희동 87-7 ,87-8",블로그리뷰 98,https://m.place.naver.com/restaurant/36462644?...,160,"{0: '아주 좋아요 ~ 자주 이용하는 편이에요', 1: '좋아요', 2: '넓고 ...","{0: 4.0, 1: 4.5, 2: 5.0, 3: 5.0, 4: 3.5, 5: 4....","{0: '2020.06.25', 1: '2020.06.23', 2: '2020.06...","{0: '1번째 방문', 1: '1번째 방문', 2: '1번째 방문', 3: '2번..."
1,스타벅스 종암DT점,종암동 29-10,블로그리뷰 26,https://m.place.naver.com/restaurant/144745971...,177,"{0: '좋아요', 1: '좋아요 ㅎㅎ', 2: '여긴 크고 작은 실수가 잦은데 학...","{0: 5.0, 1: 4.0, 2: 3.0, 3: 4.5, 4: 4.0, 5: 5....","{0: '2020.06.22', 1: '2020.06.22', 2: '2020.06...","{0: '1번째 방문', 1: '1번째 방문', 2: '1번째 방문', 3: '1번..."
2,스타벅스 영등포신길DT점,신길동 252-9 253-331253-333253-334253-335253-336,블로그리뷰 144,https://m.place.naver.com/restaurant/35886658?...,314,"{0: '만족합니다', 1: '굿', 2: '.', 3: '좋아요', 4: '좋아요...","{0: 5.0, 1: 5.0, 2: 4.5, 3: 4.0, 4: 5.0, 5: 5....","{0: '2020.06.25', 1: '2020.06.25', 2: '2020.06...","{0: '1번째 방문', 1: '1번째 방문', 2: '1번째 방문', 3: '1번..."
3,스타벅스 구의DT점,구의동 67-36,블로그리뷰 90,https://m.place.naver.com/restaurant/36636853?...,203,"{0: '좋아요', 1: '아아 마셨어요 친절 친절', 2: '.', 3: '직원들...","{0: 4.5, 1: 4.5, 2: 4.0, 3: 3.0, 4: 5.0, 5: 4....","{0: '2020.06.25', 1: '2020.06.24', 2: '2020.06...","{0: '1번째 방문', 1: '9번째 방문', 2: '1번째 방문', 3: '2번..."
4,스타벅스 낙성대DT점,봉천동 1657-3,블로그리뷰 104,https://m.place.naver.com/restaurant/38412114?...,284,"{0: '애플망고 시원하고 달달하고 상큼하니 맛나요~~', 1: '드라이브쓰루 줄 ...","{0: 3.5, 1: 3.0, 2: 5.0, 3: 4.5, 4: 5.0, 5: 5....","{0: '2020.06.25', 1: '2020.06.24', 2: '2020.06...","{0: '1번째 방문', 1: '1번째 방문', 2: '1번째 방문', 3: '1번..."
...,...,...,...,...,...,...,...,...,...
247,스타벅스 제주성산DT점,고성리 238,블로그리뷰 244,https://m.place.naver.com/restaurant/69594415?...,291,{0: '제주에만 있는 메뉴 먹으려고 방문했어요! 건물 외관도 이쁘구 창가쪽 자리가...,"{0: 5.0, 1: 5.0, 2: 3.5, 3: 4.5, 4: 2.5, 5: 4....","{0: '2020.06.25', 1: '2020.06.25', 2: '2020.06...","{0: '1번째 방문', 1: '1번째 방문', 2: '1번째 방문', 3: '1번..."
248,스타벅스 제주애월DT점,고내리 340,블로그리뷰 144,https://m.place.naver.com/restaurant/86596503?...,234,"{0: '아주좋아용', 1: '#제주도#스타벅스#애월점#무료쿠폰 득템.ㅋㅋ', 2:...","{0: 5.0, 1: 5.0, 2: 4.0, 3: 4.0, 4: 5.0, 5: 5....","{0: '2020.06.25', 1: '2020.06.25', 2: '2020.06...","{0: '1번째 방문', 1: '1번째 방문', 2: '1번째 방문', 3: '1번..."
249,스타벅스 부산교대역DT점,NaN,NaN,https://m.place.naver.com/restaurant/183480825...,3,"{0: '', 1: '새로 생긴 스벅이 담에도 또 와야징 주차창이 넘 작아요', 2...","{0: 4.0, 1: 4.5, 2: 5.0}","{0: '2020.07.08', 1: '2020.07.08', 2: '2020.07...","{0: '1번째 방문', 1: '2번째 방문', 2: '1번째 방문'}"
250,스타벅스 서귀포DT점,NaN,NaN,https://m.place.naver.com/restaurant/37053570/...,167,"{0: '맛있어용 대기가 좀 길엇어요ㅠ', 1: '굿', 2: '굿', 3: '전망...","{0: 4.5, 1: 5.0, 2: 5.0, 3: 3.0, 4: 4.0, 5: 4....","{0: '2020.07.09', 1: '2020.07.08', 2: '2020.07...","{0: '1번째 방문', 1: '8번째 방문', 2: '7번째 방문', 3: '1번..."
251,스타벅스 제주중문DT점,NaN,NaN,https://m.place.naver.com/restaurant/36952159/...,153,"{0: '', 1: '굿', 2: '굿', 3: '👍 늦게 갔더니 빵이 없네요ㅜㅜ'...","{0: 4.5, 1: 5.0, 2: 4.5, 3: 5.0, 4: 5.0, 5: 5....","{0: '2020.07.08', 1: '2020.07.08', 2: '2020.07...","{0: '1번째 방문', 1: '5번째 방문', 2: '1번째 방문', 3: '1번..."

In [33]:
from datetime import datetime
import json

In [26]:
tuple(map(lambda x:int(x),'2020.06.25'.split('.')))

(2020, 6, 25)

In [53]:
def str_to_datetime(x):
    return datetime(*(map(lambda x:int(x),x.split('.'))))

In [41]:
naver_reveiw.loc[0, 'dates'].replace("'","\"")

'{0: "2020.06.25", 1: "2020.06.23", 2: "2020.06.20", 3: "2020.06.19", 4: "2020.06.18", 5: "2020.06.12", 6: "2020.06.11", 7: "2020.06.10", 8: "2020.06.09", 9: "2020.06.09", 10: "2020.06.07", 11: "2020.06.02", 12: "2020.06.02", 13: "2020.06.02", 14: "2020.06.01", 15: "2020.06.01", 16: "2020.06.01", 17: "2020.06.01", 18: "2020.06.01", 19: "2020.06.01", 20: "2020.05.31", 21: "2020.05.31", 22: "2020.05.31", 23: "2020.05.30", 24: "2020.05.30", 25: "2020.05.27", 26: "2020.05.23", 27: "2020.05.23", 28: "2020.05.22", 29: "2020.05.21", 30: "2020.05.20", 31: "2020.05.20", 32: "2020.05.19", 33: "2020.05.19", 34: "2020.05.19", 35: "2020.05.18", 36: "2020.05.16", 37: "2020.05.16", 38: "2020.05.16", 39: "2020.05.16", 40: "2020.05.14", 41: "2020.05.14", 42: "2020.05.12", 43: "2020.05.12", 44: "2020.05.09", 45: "2020.05.08", 46: "2020.05.07", 47: "2020.05.07", 48: "2020.05.05", 49: "2020.05.04", 50: "2020.05.03", 51: "2020.05.01", 52: "2020.05.01", 53: "2020.05.01", 54: "2020.05.01", 55: "2020.05.01", 56: "2020.05.01", 57: "2020.05.01", 58: "2020.04.30", 59: "2020.04.29", 60: "2020.04.26", 61: "2020.04.26", 62: "2020.04.24", 63: "2020.04.24", 64: "2020.04.22", 65: "2020.04.21", 66: "2020.04.18", 67: "2020.04.14", 68: "2020.04.13", 69: "2020.04.11", 70: "2020.04.09", 71: "2020.04.05", 72: "2020.04.04", 73: "2020.04.02", 74: "2020.04.02", 75: "2020.04.02", 76: "2020.03.31", 77: "2020.03.29", 78: "2020.03.29", 79: "2020.03.28", 80: "2020.03.28", 81: "2020.03.23", 82: "2020.03.23", 83: "2020.03.21", 84: "2020.03.21", 85: "2020.03.20", 86: "2020.03.20", 87: "2020.03.19", 88: "2020.03.19", 89: "2020.03.18", 90: "2020.03.15", 91: "2020.03.15", 92: "2020.03.14", 93: "2020.03.09", 94: "2020.03.07", 95: "2020.03.07", 96: "2020.03.06", 97: "2020.03.04", 98: "2020.03.03", 99: "2020.03.02", 100: "2020.03.02", 101: "2020.03.02", 102: "2020.03.02", 103: "2020.03.02", 104: "2020.03.02", 105: "2020.03.02", 106: "2020.02.29", 107: "2020.02.29", 108: "2020.02.29", 109: "2020.02.27", 110: "2020.02.26", 111: "2020.02.18", 112: "2020.02.18", 113: "2020.02.18", 114: "2020.02.14", 115: "2020.02.08", 116: "2020.02.02", 117: "2020.02.01", 118: "2020.01.21", 119: "2020.01.11", 120: "2020.01.02", 121: "2020.01.01", 122: "2019.12.26", 123: "2019.12.21", 124: "2019.12.20", 125: "2019.12.17", 126: "2019.11.08", 127: "2019.11.04", 128: "2019.11.03", 129: "2019.10.19", 130: "2019.10.12", 131: "2019.10.12", 132: "2019.10.09", 133: "2019.10.05", 134: "2019.09.30", 135: "2019.09.29", 136: "2019.09.28", 137: "2019.09.25", 138: "2019.09.19", 139: "2019.09.13", 140: "2019.09.06", 141: "2019.09.03", 142: "2019.08.16", 143: "2019.07.22", 144: "2019.07.16", 145: "2019.07.06", 146: "2019.06.30", 147: "2019.06.30", 148: "2019.05.22", 149: "2019.05.18", 150: "2019.05.11", 151: "2019.05.06", 152: "2019.04.18", 153: "2019.03.07", 154: "2019.03.02", 155: "2019.03.01", 156: "2019.03.01", 157: "2019.02.26", 158: "2019.02.24", 159: "2018.09.26"}'

In [112]:
ast.literal_eval(naver_reveiw.loc[0, 'dates']).values()

dict_values(['2020.06.25', '2020.06.25', '2020.06.23', '2020.06.22', '2020.06.22', '2020.06.21', '2020.06.21', '2020.06.19', '2020.06.19', '2020.06.18', '2020.06.18', '2020.06.17', '2020.06.17', '2020.06.16', '2020.06.16', '2020.06.16', '2020.06.15', '2020.06.15', '2020.06.15', '2020.06.15', '2020.06.15', '2020.06.14', '2020.06.14', '2020.06.14', '2020.06.14', '2020.06.14', '2020.06.13', '2020.06.13', '2020.06.12', '2020.06.12', '2020.06.11', '2020.06.11', '2020.06.10', '2020.06.10', '2020.06.10', '2020.06.10', '2020.06.09', '2020.06.08', '2020.06.08', '2020.06.08', '2020.06.08', '2020.06.08', '2020.06.08', '2020.06.07', '2020.06.07', '2020.06.07', '2020.06.07', '2020.06.03', '2020.06.03', '2020.06.02', '2020.06.02', '2020.06.01', '2020.05.31', '2020.05.31', '2020.05.31', '2020.05.30', '2020.05.29', '2020.05.29', '2020.05.29', '2020.05.28', '2020.05.28', '2020.05.27', '2020.05.27', '2020.05.26', '2020.05.26', '2020.05.25', '2020.05.25', '2020.05.25', '2020.05.24', '2020.05.23', '2020.05.23', '2020.05.22', '2020.05.21', '2020.05.20', '2020.05.17', '2020.05.16', '2020.05.16', '2020.05.15', '2020.05.14', '2020.05.10', '2020.05.10', '2020.05.10', '2020.05.09', '2020.05.02', '2020.05.01', '2020.05.01', '2020.04.30', '2020.04.30', '2020.04.29', '2020.04.27', '2020.04.26', '2020.04.26', '2020.04.26', '2020.04.26', '2020.04.25', '2020.04.25', '2020.04.19', '2020.04.18', '2020.04.15', '2020.04.12', '2020.04.10', '2020.04.06', '2020.04.03', '2020.04.03', '2020.04.02', '2020.04.01', '2020.03.30', '2020.03.29', '2020.03.29', '2020.03.26', '2020.03.25', '2020.03.25', '2020.03.23', '2020.03.19', '2020.03.18', '2020.03.14', '2020.03.13', '2020.03.12', '2020.03.11', '2020.03.08', '2020.03.03', '2020.03.03', '2020.03.02', '2020.03.01', '2020.02.28', '2020.02.26', '2020.02.25', '2020.02.25', '2020.02.24', '2020.02.23', '2020.02.22', '2020.02.22', '2020.02.22', '2020.02.22', '2020.02.14', '2020.02.14', '2020.02.11', '2020.02.10', '2020.02.09', '2020.01.31', '2020.01.30', '2020.01.28', '2020.01.25', '2020.01.24', '2020.01.24', '2020.01.23', '2020.01.23', '2020.01.22', '2020.01.13', '2020.01.13', '2020.01.12', '2020.01.08', '2020.01.07', '2020.01.02', '2020.01.01', '2019.12.16', '2019.12.16', '2019.12.14', '2019.12.09', '2019.12.09', '2019.12.09', '2019.12.08', '2019.12.06', '2019.12.06', '2019.12.02', '2019.11.30', '2019.11.30', '2019.11.22', '2019.11.18', '2019.11.13', '2019.11.11', '2019.11.06', '2019.11.05', '2019.11.05', '2019.11.01', '2019.10.20', '2019.10.19', '2019.10.18', '2019.10.16', '2019.10.16', '2019.10.15', '2019.10.11', '2019.10.09', '2019.10.08', '2019.10.08', '2019.10.08', '2019.10.08', '2019.10.08', '2019.10.08', '2019.10.08', '2019.10.08', '2019.10.06', '2019.10.05', '2019.10.04', '2019.09.30', '2019.09.30', '2019.09.26', '2019.09.23', '2019.09.23', '2019.09.17', '2019.09.16', '2019.08.31', '2019.08.30', '2019.08.28', '2019.08.27', '2019.08.26', '2019.08.18', '2019.08.04', '2019.07.21', '2019.07.19', '2019.06.29', '2019.06.27', '2019.06.22', '2019.06.22', '2019.06.12', '2019.06.06', '2019.05.25', '2019.05.25', '2019.05.23', '2019.05.17', '2019.05.17', '2019.05.05', '2019.04.16', '2019.04.04', '2019.03.31', '2019.03.03', '2019.02.27', '2019.01.01', '2018.12.18', '2018.10.30', '2018.07.28', '2018.06.04', '2018.01.06'])

In [49]:
import ast
# ast.literal_eval(naver_reveiw.loc[0, 'dates'])

In [69]:
cnt = 0
date = '2020.04.01'
base_date = str_to_datetime(date)
naver_reveiw[date+'이후 영수증 개수'] = 0

receipt_map = {'6개월 영수증 개수' : [0, '2019.12.23'],
               '3개월 영수증 개수' : [0, '2020.03.23'],
               '2개월 영수증 개수' : [0, '2020.04.23'],
               '1개월 영수증 개수' : [0, '2020.05.23']}
for x in receipt_map:
    naver_reveiw[x]=''

In [119]:
row_scores = ast.literal_eval(row['scores'])
row_scores[0]

4.0

In [121]:

for idx, row in naver_reveiw.iterrows():
    receipt_map = {
               '1년 영수증 개수' : [0, '2019.06.23'],
               '6개월 영수증 개수' : [0, '2019.12.23'],
               '3개월 영수증 개수' : [0, '2020.03.23'],
               '2개월 영수증 개수' : [0, '2020.04.23'],
               '1개월 영수증 개수' : [0, '2020.05.23']}
    receipt_score = ['1년 점수', '6개월 점수', '3개월 점수', '2개월 점수', '1개월 점수']
    scores = [0, 0, 0, 0, 0]
    row_scores = ast.literal_eval(row['scores'])
#     print(f'receipt number after {base_date} : {cnt}')
    for k, date in ast.literal_eval(row['dates']).items():
        for i, (map_col, date_info) in enumerate(receipt_map.items()):
            if str_to_datetime(date) >= str_to_datetime(date_info[1]):
                date_info[0]+=1
                scores[i]+=float(row_scores[k])
    for i, (map_col, date_info) in enumerate(receipt_map.items()):
        naver_reveiw.loc[idx, map_col] = date_info[0]
        naver_reveiw.loc[idx, receipt_score[i]] = scores[i] / date_info[0]
    
#     print(f'영수증 개수 : {naver_reveiw.loc[idx, list(receipt_map.keys())]}')

In [131]:
naver_reveiw_ext = naver_reveiw[[naver_reveiw.columns[1]] + list(naver_reveiw.columns[-10:])].sort_values('6개월 점수', ascending=False)

In [147]:
naver_reveiw_ext = naver_reveiw_ext[naver_reveiw_ext['1개월 영수증 개수'] > 0].sort_values('loc_name').reset_index(drop=True)

In [148]:
naver_reveiw_ext.to_excel('../starbucksDT/postprocess/starbucks_naver_review_analysis_200710.xlsx', index=False)